name: Neptune actions

on: [push]

jobs:
  compare-experiments:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    env:
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
      NEPTUNE_PROJECT_NAME: ${{ secrets.NEPTUNE_PROJECT_NAME }}

    steps:


      - name: Setup pull request branch environment and run experiment
        id: experiment_pr
        run: |
          export NEPTUNE_EXPERIMENT_TAG_ID=$(uuidgen)
          docker build -t hhurchand/bdebneptunelocal:latest .
          docker run  hhurchand/bdebneptunelocal:latest
          echo ::set-output name=experiment_tag_id::$NEPTUNE_EXPERIMENT_TAG_ID

